const fs = require('fs');
const os = require('os');
const path = require('path');
const hook = require('../hooks/ios/updatePodsDeploymentTarget');

const CORDOVA_PODFILE = [
  '# DO NOT MODIFY -- auto-generated by Apache Cordova',
  'source \'https://cdn.cocoapods.org/\'',
  'platform :ios, \'13.0\'',
  'use_frameworks!',
  'target \'App\' do',
  '\tproject \'App.xcodeproj\'',
  '\tpod \'FirebaseMessaging\', \'12.19.0\'',
  'end',
  ''
].join('\n');

const countOf = (str, sub) => str.split(sub).length - 1;

describe('iOS hook: updatePodsDeploymentTarget', () => {
  describe('resolveDeploymentTarget', () => {
    it('should clamp low or missing values to 15.0', () => {
      expect(hook.resolveDeploymentTarget('9.0')).toBe('15.0');
      expect(hook.resolveDeploymentTarget('13.0')).toBe('15.0');
      expect(hook.resolveDeploymentTarget(undefined)).toBe('15.0');
      expect(hook.resolveDeploymentTarget('invalid')).toBe('15.0');
    });

    it('should respect higher configured values', () => {
      expect(hook.resolveDeploymentTarget('15.0')).toBe('15.0');
      expect(hook.resolveDeploymentTarget(' 16.4 ')).toBe('16.4');
      expect(hook.resolveDeploymentTarget('17')).toBe('17');
    });
  });

  describe('updatePodfileContents', () => {
    it('should append a post_install block when none exists', () => {
      const result = hook.updatePodfileContents(CORDOVA_PODFILE, '15.0');
      expect(result.startsWith(CORDOVA_PODFILE)).toBe(true);
      expect(countOf(result, 'post_install do |installer|')).toBe(1);
      expect(result).toContain('config.build_settings[\'IPHONEOS_DEPLOYMENT_TARGET\'] = \'15.0\'');
    });

    it('should be idempotent', () => {
      const once = hook.updatePodfileContents(CORDOVA_PODFILE, '15.0');
      expect(hook.updatePodfileContents(once, '15.0')).toBe(once);
    });

    it('should update the existing block when the target changes', () => {
      const once = hook.updatePodfileContents(CORDOVA_PODFILE, '15.0');
      const twice = hook.updatePodfileContents(once, '16.0');
      expect(countOf(twice, 'post_install do')).toBe(1);
      expect(twice).toContain('\'16.0\'');
      expect(twice).not.toContain('\'15.0\'');
    });

    it('should merge into an existing post_install block', () => {
      const podfile = `${CORDOVA_PODFILE}post_install do |pi|\n  puts 'custom'\nend\n`;
      const result = hook.updatePodfileContents(podfile, '15.0');
      expect(countOf(result, 'post_install do')).toBe(1);
      expect(result).toContain('pi.pods_project');
      expect(result).toContain('puts \'custom\'');
      expect(hook.updatePodfileContents(result, '15.0')).toBe(result);
    });
  });

  describe('updatePbxprojContents', () => {
    it('should only raise values lower than the target', () => {
      const input = [
        'IPHONEOS_DEPLOYMENT_TARGET = 9.0;',
        'IPHONEOS_DEPLOYMENT_TARGET = 12.0;',
        'IPHONEOS_DEPLOYMENT_TARGET = "12.0";',
        'IPHONEOS_DEPLOYMENT_TARGET = 16.0;'
      ].join('\n');
      expect(hook.updatePbxprojContents(input, '15.0')).toBe([
        'IPHONEOS_DEPLOYMENT_TARGET = 15.0;',
        'IPHONEOS_DEPLOYMENT_TARGET = 15.0;',
        'IPHONEOS_DEPLOYMENT_TARGET = "15.0";',
        'IPHONEOS_DEPLOYMENT_TARGET = 16.0;'
      ].join('\n'));
    });
  });

  describe('hook', () => {
    let projectRoot;
    let iosRoot;
    let context;

    beforeEach(() => {
      projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'push-hook-'));
      iosRoot = path.join(projectRoot, 'platforms', 'ios');
      fs.mkdirSync(path.join(iosRoot, 'Pods', 'Pods.xcodeproj'), { recursive: true });
      fs.writeFileSync(path.join(iosRoot, 'Podfile'), CORDOVA_PODFILE);
      fs.writeFileSync(
        path.join(iosRoot, 'Pods', 'Pods.xcodeproj', 'project.pbxproj'),
        'IPHONEOS_DEPLOYMENT_TARGET = 9.0;\nIPHONEOS_DEPLOYMENT_TARGET = 12.0;\n'
      );
      context = {
        opts: { projectRoot },
        requireCordovaModule: () => { throw new Error('unavailable'); }
      };
      spyOn(console, 'log');
    });

    afterEach(() => {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    });

    it('should update the Podfile and Pods project idempotently', () => {
      hook(context);
      const podfile = fs.readFileSync(path.join(iosRoot, 'Podfile'), 'utf8');
      const pbxproj = fs.readFileSync(path.join(iosRoot, 'Pods', 'Pods.xcodeproj', 'project.pbxproj'), 'utf8');
      expect(countOf(podfile, 'post_install do')).toBe(1);
      expect(pbxproj).toBe('IPHONEOS_DEPLOYMENT_TARGET = 15.0;\nIPHONEOS_DEPLOYMENT_TARGET = 15.0;\n');

      hook(context);
      expect(fs.readFileSync(path.join(iosRoot, 'Podfile'), 'utf8')).toBe(podfile);
    });

    it('should use the configured deployment target when higher than 15.0', () => {
      context.requireCordovaModule = () => ({
        ConfigParser: function () {
          this.getPreference = (name, platform) => (name === 'deployment-target' && platform === 'ios' ? '16.0' : '');
        }
      });
      hook(context);
      expect(fs.readFileSync(path.join(iosRoot, 'Podfile'), 'utf8')).toContain('= \'16.0\'');
      expect(fs.readFileSync(path.join(iosRoot, 'Pods', 'Pods.xcodeproj', 'project.pbxproj'), 'utf8'))
        .toBe('IPHONEOS_DEPLOYMENT_TARGET = 16.0;\nIPHONEOS_DEPLOYMENT_TARGET = 16.0;\n');
    });

    it('should do nothing without a Podfile', () => {
      fs.unlinkSync(path.join(iosRoot, 'Podfile'));
      expect(() => hook(context)).not.toThrow();
    });
  });
});
